owner: kopeio
repo: build
assets:
  - source: bazel-bin/cmd/kcb/darwin_amd64_pure_stripped/kcb
    githubName: kcb-darwin-amd64
  # - source: bazel-bin/cmd/kcb/darwin_amd64_pure_stripped/kcb.sha1
  #   githubName: kcb-darwin-amd64-sha1
  - source: bazel-bin/cmd/kcb/linux_amd64_stripped/kcb
    githubName: kcb-linux-amd64
  # - source: bazel-bin/cmd/kcb/linux_amd64_stripped/kcb.sha1
  #   githubName: kcb-linux-amd64-sha1
